config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  resources :articles do
    resources :comments
  end

  resources :users do
    resources :articles
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include ArticleVisibility

  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true

  scope :public_posts, -> { where(status: 'public') }
  scope :order_by_date, ->(sort = 'asc') { reorder("created_at #{sort}") }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include ArticleVisibility

  belongs_to :article
  belongs_to :user

  validates :user_id, presence: true
  validates :article_id, presence: true
end

app/models/concerns/article_visibility.rb
# frozen_string_literal: true

module ArticleVisibility
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :articles

  scope :users_with_articles, -> { joins(:articles).group('user_id') }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # only the index page should be available for non logged in users should see
  # If user tried to access any route such as /articles without being logged in
  # User is sent to login page
  before_action :authenticate_user!

  def after_sign_in_path_for(_resource)
    articles_path # your path
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :public_articles, only: %i[index show]
  before_action :users_with_articles, only: [:index]

  def index
    @current_user_articles = current_user&.articles&.order_by_date params[:sort]
  end

  def show
    @article = current_user&.articles&.find_by(params[:id])
    @article = if @article.present? && @article.status.eql?('private')
                 @article_private
               else
                 @public_articles.find(params[:id])
               end
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy

    redirect_to articles_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

  def public_articles
    @public_articles = Article.public_posts&.order_by_date params[:sort]
  end

  def users_with_articles
    @users_with_articles = User.users_with_articles
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  # before_action is a filter, which is a method used when controller is called.
  # Since we want the filter to run before any action is taken, it is before_action
  before_action :authenticate_user!, except: [:index]
  before_action :current_article, only: [:create]
  before_action :current_comment, except: [:update, :create]
  # :except => [:index] allows all users to access index route but only authenticated users
  # can access other routes in the comments controller.

  def create
    @comment = @article.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save!
    redirect_to article_path(@article)
  end

  def destroy
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  def edit
  end

  def update
    @article = current_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def show
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end

  def current_article
    @article = Article.find(params[:article_id])
  end

  def current_comment
    @comment = current_article.comments.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    render text: :hiiii
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def format_time(timestamp)
    timestamp.strftime('%d/%m/%Y %H:%M')
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/articles/_form.html.erb
<% if article.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(article.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% article.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>
<!-- :model arugment binds formbulider to model object.
     form scoped to article, form fields populated by values from article -->
<div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
  <%= form_with model: article do |form| %>
    <!-- article[status] -->
    <p>
      <%= form.label :status %><br>
      <!-- select sets default select option, in this case by default is "public" -->
      <%= form.select :status, ['public', 'private'], selected: 'public' %>
    </p>

    <!-- article[title] -->
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <!-- article[body] -->
    
    <div class="d-flex flex-start w-100">
      <div class="form-outline w-100">
        <%= form.label(:body, class: "form-label") %><br>
        <%= form.text_area(:body, class: "form-control", rows: "4", style: "background: #fff;")%>
      </div>
    </div>

    <div class="float-end mt-2 pt-1">
      <%= form.submit(class: "btn btn-primary btn-sm") %>
    </div>
  <% end %>
</div>

app/views/articles/_list.html.erb
<div class="col-md-8">
    <h3 class="pb-4 mb-4 mt-4 fst-italic border-bottom">
    <%= title %>
    </h3>
</div>

<% if title == "All Articles"%>
    <% users.each do |user| %>
        <%= link_to "#{user.first_name}", :selected_user => user %>
    <% end %>
<% end %>


<%= link_to "Descending order", :sort => "desc"%> </th>
<%= link_to "Ascending order", :sort => "asc"%> </th>

<div class="row mb-2">
    <% articles.each_with_index do |article, index| %>
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <% if current_user&.id == article.user_id %>
            <strong>
                <%= link_to "Edit", edit_article_path(article), class: "d-inline-block mb-2 text-primary text-decoration-none"%>
                <%= link_to "Destroy", article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    },  class: "text-decoration-none text-danger" %>
            </strong>
            <% end %>
            <h3 class="mb-0"><%= article.title %></h3>
            <div class="mb-1 text-muted"><%= format_time(article.created_at) %></div>
            <p class="card-text mb-auto"><%= truncate(article.body, length: 200) %></p>
            <%= link_to "Continue reading", article, class: "stretched-link"%>
        </div>
        </div>
    </div>
    <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render partial: "form", locals: {article: @article}%>

app/views/articles/index.html.erb
<!-- inside app/views/home/index.html.erb -->

<main class="container">
<% if current_user.present? %>
  <div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mt-4 fst-italic border-bottom">
        <%= link_to "New Article", new_article_path%>
      </h3>
    </div>
    <!-- sort option for articles -->
    
    <!-- Users articles -->
    <%= render partial: 'list', locals: {articles: @current_user_articles, title: "My Articles", users: @users_with_articles}%>
  <% end %>
  <!-- All Users Public Articles -->
  <%= render partial: 'list', locals: {articles: @public_articles, title: "All Articles", users: @users_with_articles}%>
</main>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render partial: "form", locals: {article: @article, b: 1} %>

app/views/articles/show.html.erb
<section style="background-color: #eee;">
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10 col-xl-8">
        <!-- Article display -->
        <div class="row g-5">
          <div class="col-md-8">
            <article class="blog-post">
              <h2 class="blog-post-title"><%= @article.title %></h2>
              <p class="blog-post-meta"><%= format_time(@article.created_at) %></p>
              <hr>
              <p><%= @article.body %></p>
              <hr>
              <% if current_user&.id == @article.user_id%>
              <%= link_to "Edit", edit_article_path(@article) %>
              <%= link_to "Destroy", article_path(@article), data: {
                          turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                        } %>
              <% end %>          
            </article>
          </div>
        </div>
        <!-- Comments displaying -->
        <div class="card mt-4">
          <%= render @article.comments %>
          <% if current_user.present? %>
          <hr>
          <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <%= render partial: 'comments/form', locals: {article: @article} %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <div class="card-body">
    <div class="d-flex flex-start align-items-center">
      <div>
        <h6 class="fw-bold text-primary mb-1"><%= comment.commenter %></h6>
        <p class="text-muted small mb-0">
          <%= format_time(comment.created_at) %>
        </p>
      </div>
    </div>

    <p class="mt-3 mb-4 pb-2">
      <%= comment.body %>
    </p>


    <% if current_user&.id == comment.article.user_id || current_user&.id == comment.user_id %>
      <div class="small d-flex justify-content-start">
        <%= link_to "Delete Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }, class: "text-danger" %>
        <% if current_user&.id == comment.user_id %>        
          <%= link_to "Edit", edit_article_comment_path(@article) %>
        <% end %>  
      </div>
    <% end %>  
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
  <%= form_with model: [ article, article.comments.build ], :remote => true do |form| %>
    <p>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private'], selected: 'public' %>
    </p>
    <% if user_signed_in? %>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter, value: current_user.first_name, readonly: true %>
    <% else %>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter%>
    <% end %>
    <div class="d-flex flex-start w-100">
      <div class="form-outline w-100">
        <%= form.label(:body, class: "form-label") %><br>
        <%= form.text_area(:body, class: "form-control", rows: "4", style: "background: #fff;")%>
      </div>
    </div>

    <div class="float-end mt-2 pt-1">
      <%= form.submit(class: "btn btn-primary btn-sm") %>
    </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render partial: 'form', locals: {article: @article}%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
    <div class="container-fluid">
        <%= link_to "Home", articles_path, class: "navbar-brand" %>
        <!-- navbar elements -->
        <ul class="navbar-nav ms-auto">
            <% if user_signed_in?%>
                    <%= button_to "Sign out", destroy_user_session_path, method: :delete, form: {turbolink: false}, class: "mt-1 mx-2" %>
            <% else %>
                <%= button_to "Sign in", new_user_session_path, form: {turbolink: false}, class: "mt-1 mx-2" %>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Csstest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style.css' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
  

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>